language: node_js
node_js:
- 6
os:
- linux
- osx
before_install:
- npm install -g @andreypopp/esy
install:
- esy install
script:
- esy build
- esy ./_build/bin/hello.byte
- esy ./_build/bin/hello.native

